### ISSUE TITLE
Wrap POST response JSON in {'data': ... } object

### ISSUE THREAD

**Issue by chalin** [adaojunior/http_in_memory_web_api#1]
It would be better to conform to [security best practices](https://www.owasp.org/index.php/OWASP_AJAX_Security_Guidelines#Always_return_JSON_with_an_Object_on_the_outside), as is done by [a2-in-memory-web-api](https://github.com/wardbell/a2-in-memory-web-api), by wrapping POST response JSON [as is done for get](https://github.com/adaojunior/http-in-memory-web-api/blob/master/lib/src/in_memory_backend_service.dart#L103):

``` dart
Response _get(RequestInfo req) {
    ...
    final body = JSON.encode({'data': data}); // <<<<<<<<<<<<<<<<<<
    return new Response(body, STATUS['OK'], headers: req.headers);
  }
```

**Comment by adaojunior** [comment]
@chalin thanks, sorry for the delay, I didnt get notified on this issue.

**Comment by chalin** [comment]
np. Will you be working on it now? (Just FMI)

**Comment by adaojunior** [comment]
Yes :D thank you for reporting this issue
